name: Copy Files from Private Repo  
  
on:  
  workflow_dispatch:  # 手动触发工作流  
  # 你也可以设置定时触发，比如每天凌晨 1 点：  
  # schedule:  
  #   - cron: '0 1 * * *'  
  
jobs:  
  copy-files:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout target repository  
        uses: actions/checkout@v2  
        with:  
          path: target-repo  
  
      - name: Set up Git credentials  
        run: |  
          git config --global url."https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"  
          echo "GITHUB_TOKEN=${PERSONAL_ACCESS_TOKEN}" >> ${GIT_CONFIG}  
        env:  
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # 确保在仓库的 Secrets 中存储了这个 PAT  
          GIT_CONFIG: $(mktemp)  
  
      - name: Clone private repository  
        run: |  
          git clone https://github.com/168xx/zdgx.git private-repo  
          cd private-repo  
          # 假设你的私有仓库的默认分支是 main  
          git checkout main  
  
      - name: Copy .txt and .m3u files to target repository  
        run: |  
          cp -r private-repo/tv/*.txt private-repo/tv/*.m3u target-repo/live/  
  
      - name: Commit and push changes  
        run: |  
          cd target-repo  
          git config --local user.email "your-email@example.com"  
          git config --local user.name "your-username"  
          git add live/  
          git commit -m "Copied .txt and .m3u files from private repository" || true  
          git push