name: Copy Files from Private Repo  
  
on:  
  workflow_dispatch:  
  
jobs:  
  copy-files:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  
    steps:  
      - name: Checkout Main Repo  
        uses: actions/checkout@v3  
  
      - name: Set up Python  
        uses: actions/setup-python@v3  
        with:  
          python-version: '3.x'  
  
      - name: Clone Private Repo  
        env:  
          PRIVATE_REPO_URL: ${{ secrets.PRIVATE_REPO_URL }}  
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}  
        run: |  
          git clone https://${PRIVATE_REPO_PAT}:x-oauth-basic@github.com/${PRIVATE_REPO_URL}.git private-repo  
  
      - name: Copy Specific Files  
        run: |  
          python3 copy_files.py private-repo/path/to/source main-repo-files  # 替换为私有仓库中的源路径和目标目录  
        working-directory: ${{ github.workspace }}  
  
      - name: Stage Changes  
        run: |  
          git config --local user.email "github-actions@github.com"  
          git config --local user.name "github-actions"  
          # 只添加 main-repo-files 目录下的 .txt 和 .m3u 文件  
          find main-repo-files -type f \( -iname "*.txt" -o -iname "*.m3u" \) -exec git add {} \;  
  
      - name: Commit and Push Changes  
        run: |  
          if [ -n "$(git status --porcelain)" ]; then  
            git commit -m "Copied files from private repo"  
            git push  
          else  
            echo "No changes to commit"  
          fi