name: Fetch TXT Files  
  
on:  
  workflow_dispatch:  # You can trigger this workflow manually from the GitHub UI  
  # Uncomment the following line to run the workflow on a schedule, e.g., every day at midnight  
  # schedule:  
  #   - cron: '0 0 * * *'  
  
jobs:  
  fetch-txt-files:  
    runs-on: ubuntu-latest  
  
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}  # Use the secret you created in the repository settings  
  
    steps:  
    - name: Checkout the current repository  
      uses: actions/checkout@v2  
  
    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: '3.x'  
  
    - name: Install dependencies  
      run: |  
        python -m pip install --upgrade pip  
        # Install any other dependencies if needed  
  
    - name: Fetch and copy TXT files  
      run: |  
        python fetch_txt_files.py  
  
    - name: Commit and push changes  
      run: |  
       git config --local user.email "actions@126.com"
       git config --local user.name "GitHub Action"
        git add IP/  
        git commit -m "Fetched TXT files from private repository" || true  
        git push